# Audio version constants

CSB_JON_MOHR: str = "audio audio/csb"
ESV_MAX_MCLEAN: str = "audio mclean/esv"
ESV_MARQUIS_LAUGHLIN: str = "audio laughlin/esv"
GNV_STEVE_COOK: str = "audio cook/gnv"
HCSB_DALE_MCCONACHIE: str = "audio mcconachie/hcsb"
KJV_MAX_MCLEAN: str = "audio mclean/kjv"
KJV_PAUL_MIMS: str = "audio mims/kjv"
KJV_DRAMATIZED: str = "audio dramatized/kjv"
LEB_LOGOS: str = "audio logos/leb"
MSG_KELLY_RYAN_DOLAN: str = "audio dolan/msg"
NASB_DALE_MCCONACHIE: str = "audio mcconachie/nasb"
NASB1995_DALE_MCCONACHIE: str = "audio mcconachie/nasb1995"
NIV_MAX_MCLEAN: str = "audio mclean/niv"
NIV_DRAMATIZED: str = "audio dramatized/niv"
NIV_GEORGE_W_SARRIS: str = "audio purevoice/niv"
NIVUK_DAVID_SUCHET: str = "audio suchet/nivuk"
NKJV_SIMON_BUBB: str = "audio bubb/nkjv"
NKJV_TINASHA_LARAYE: str = "audio laraye/nkjv"
NLT_BREATHE: str = "audio breathe/nlt"
